server {
    listen 80;
    server_name _;

    location /parking/ {
        alias /usr/share/nginx/html/parking/;
        try_files $uri =404;
        add_header Cache-Control "no-store" always;
    }
}
